### ISSUE TITLE
Configure split_words for all env vars

### ISSUE THREAD

**Issue by Rossiar** [kelseyhightower/envconfig#104]
My application uses `envconfig` with a configuration struct like this:
```
// Config provides the configuration for this application
type Config struct {
	AppName string `split_words:"true"`
	Env string

	MongoPoolSize int `split_words:"true"`
	MongoPort string `split_words:"true"`
	MongoUri string `required:"true" split_words:"true"`

	Port int
	Version string
}
```

It would be useful to have an option that I could pass to the `Process/MustProcess` functions to configure the `split_words` behaviour for all variables, so that I can cut down on boilerplate in my struct tags.

I'm happy to work on a PR for this once this issue is acknowledged.

**Comment by teepark** [comment]
I think this complicates the API too much. We already have multiple ways to accomplish the same thing: `envconfig:"MONGO_POOL_SIZE"` vs `split_words:"true"`. Mixing `Process`-level configuration with the field-wise configs we already have introduces a lot more potential for confusion. I assume the intention is that field tags would still override the global configuration? What about a global `split_words` mixed with `envconfig` field tags? That's nonsensical. As it is, one can look at the struct definition and see everything they need to know about its deserialization, just like the norm with other serdes libraries (json, yaml, etc).
