### ISSUE TITLE
Getting Env Variables Not Working.

### ISSUE THREAD

**Issue by mdere** [kelseyhightower/envconfig#112]
Morning - so I have the following:

```
type Specification struct {
    Hostname        string
    // RDBMSDBUser     string
    // RDBMSDBPassword string
}

func GetConf() Specification {
    var s Specification
    err := envconfig.Process("myapp", &s)
    if err != nil {
        panic(err.Error())
    }
    log.Log("#######################")
    log.Log(s)
    log.Log(&s)

    // s.Hostname, s.RDBMSDBUser, s.RDBMSDBPassword
    return s
}
```

and I am running my app in docker - so it is running it as root - so I assume I need to export those variables as root, also I did it as my primary user too.

```
root@mdere-VirtualBox:/home/mdere# echo $MYAPP_HOSTNAME
localhost:8080

mdere:~$ echo $MYAPP_HOSTNAME
localhost:8080
```

the logs are spitting out {} or &{} for s variable

**Comment by schahal** [comment]
> and I am running my app in docker

But the `echo` of your environment variable seem to be run on the host. Are you sure you're passing/setting the environment variable `$MYAPP_HOSTNAME` into the docker container as well?

**Comment by teepark** [comment]
I can get your example working @mdere, I think as @schahal suggested it's a matter of having the environment variables actually visible to your application.
