### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ricardogama** [kelseyhightower/envconfig#114]
Hi.

I see the latest tag is 12 behind the current master branch.

The feature I'm looking for is not having to specify the prefix on `envconfig.Process()` in snake case format. It seems odd to specify the env prefix like `my_app` where `MY_APP` is the standard format to specify environment variables.

I see this is fixed on master branch though, so since locking versions is always a good practice, when a new tag can be expected?

Cheers!

**Comment by johanbrandhorst** [comment]
Bump. Would like a new release with https://github.com/kelseyhightower/envconfig/commit/dfd2ad3cd15188efad40daf9d01d975cb0dda7fc.

**Comment by a8m** [comment]
@kelseyhightower - Is there any chance to create a new release? It’ll make the work with dep/vgo much easier. 

Thanks

**Comment by 8tomat8** [comment]
@kelseyhightower @teepark, Hey guys. Do you have any plans to support this repository?
Are there any issues with the latest code that blocks you from the creation of new releases?

**Comment by marco-m** [comment]
This is a dup of #132

**Comment by teepark** [comment]
`v1.4.0` is out! 🎉
