### ISSUE TITLE
Need two parsing funcs instead of one

### ISSUE THREAD

**Issue by yuliabaron** [kelseyhightower/envconfig#117]
I came across the need to have two separate Process functions: one for default values, and another for env values. The reason is that sometimes there're other config sources (like config file), and in this case env value is used as a custom runtime option. If that's ok I can add a PR with these two functions

**Comment by teepark** [comment]
I don't think that's going to be very clear from an API standpoint.

Your best bet is probably to dedicate a config struct to environment configuration, **not** use default values, and conditionally overwrite your file-based configs based on the fields that were actually populated.
