### ISSUE TITLE
split_words == true as default?

### ISSUE THREAD

**Issue by drbwa** [kelseyhightower/envconfig#122]
Would it make sense to have `split_words` equal to true as the default? Assuming environment variable names whose parts are split (e.g., MONGO_URI, SERVER_PORT) may be more readable. 

Unless there is a reason this does not make sense as the default, I would be happy to submit a corresponding PR.

What do you think?

**Comment by markphelps** [comment]
Or perhaps a new `ProcessX` function that takes options? One of the options being to `split_words` for all fields?

**Comment by rdsubhas** [comment]
@markphelps and maybe the current `prefix` could also be consumed as an option in the `ProcessX` function. Looks nice! Except there will now be potentially two methods to do the same thing...

@kelseyhightower what do you think about this?

**Comment by teepark** [comment]
This possibly would have been a better call from the beginning, but I don't think it's a good enough reason to break backwards compatibility.
