### ISSUE TITLE
Names are split incorrectly with split_words and uppercase words

### ISSUE THREAD

**Issue by mafredri** [kelseyhightower/envconfig#125]
For a struct field like `JSONFile`, envconfig expects the environment variable to be named `JSONF_ILE`. This seems like a bug and would encourage writing `JsonFile` instead (which is against golint).

Expected result: `JSON_FILE`.

Example:

```go
spec := struct {
	JSONFile string `split_words:"true"`
}{}
envconfig.Usage("", &spec)
```

Version: master (dd1402a4d99de9ac2f396cd6fcb957bc2c695ec1)

**Comment by teepark** [comment]
fixed with #140 -- good find @mafredri
