### ISSUE TITLE
Nested maps and lists are not supported

### ISSUE THREAD

**Issue by andrewslotin** [kelseyhightower/envconfig#137]
In [Supported Struct Field Types](https://github.com/kelseyhightower/envconfig#supported-struct-field-types) section of README it's being said that any supported type field type can be used as a map/list value. However, current implementation does not allow the use of nested maps and lists, i.e. the following example will result with an error:
```go
package main
type Config struct {
	Map map[string]map[string]string
}

func main() {
	var cfg Config
	if err := envconfig.Process("config", &cfg); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%#v\n", cfg.Map)
}
```
```bash
$ CONFIG_MAP=key1:key2:1 go run main.go
envconfig.Process: assigning CONFIG_MAP to Map: converting 'key1:key2:1' to type map[string]map[string]string. details: invalid map item: "key1:key2:1"
```

It looks like this is due [the way how map/list values are parsed](https://github.com/kelseyhightower/envconfig/blob/dd1402a4d99de9ac2f396cd6fcb957bc2c695ec1/envconfig.go#L308-L313) right now. While it allows to use a simple syntax to specify non-scalar values, it also limits the types that can be used as values and even puts restrictions on values themselves (I guess that it's also impossible to use a string that contains `:` or `,` as key/map value).

**Comment by teepark** [comment]
It's only kind of half-true that nested data structures aren't supported. You could totally implement a [custom decoder](https://github.com/kelseyhightower/envconfig#custom-decoders) and handle eg JSON-encoded environment variables.

Since that general swiss army knife is available I don't really see building this directly.

**Comment by dtracers** [comment]
it would be nice if the documentation was updated to say:

"slices of any non nesting supported type*"
"maps (keys and values of any non nesting supported type*)"

then later on had a *maps and lists can be made nested using custom decoders are but not built into the library.

I did not realize they were not supported natively until I ran across this issue
