### ISSUE TITLE
Byte slices from strings

### ISSUE THREAD

**Issue by mickeyreiss** [kelseyhightower/envconfig#141]
`Foo []byte` config variables need to be set as `FOO=1,2,3`. This makes sense technically, but it's a bit unintuitive. I would like to pass in `[]byte` values as a string (or perhaps a base64 encoded string.)

I know this request potentially breaks compatibility, so maybe it's too late to make this change to the library. Thought I'd pass on the feedback nonetheless.

Thanks!

**Comment by teepark** [comment]
I think this is reasonable @mickeyreiss. Both approaches (treating `[]byte` as like `string` or like `[]anythingelse`) make sense, but the former is probably the more commonly desired behavior.

**Comment by mickeyreiss** [comment]
Thanks 🎉
