### ISSUE TITLE
Feature Request: Ability to get list of ENV variables

### ISSUE THREAD

**Issue by MistaTwista** [kelseyhightower/envconfig#176]
# Feature Request
It may be helpful if **envconfig** can provide list of env variables for config struct. It can be just []string with list of vars or even more smarty, []EnvVar, like:
```golang
type EnvVar struct {
  Name string
  Required bool
  Ignored bool
  SplitWords bool
  Default string
  etc...
}
```
so user can do whatever he needs with this list

# Motivation

When new developer started to work with project or DevOps team wants to get list of configurable ENV or we just wanted to have actual documentation about ENV configurable variables.

# Example

Something like

```golang
type Specification struct {
    ManualOverride1 string `envconfig:"manual_override_1"`
    DefaultVar string `default:"foobar"`
    RequiredVar string `required:"true"`
    IgnoredVar string `ignored:"true"`
    AutoSplitVar string `split_words:"true"`
    RequiredAndAutoSplitVar string `required:"true" split_words:"true"`
}

var s Specification
list := envconfig.ExtractList("myapp", &s)
```

So the list will have full list of ENV vars that can configure our App

What do you think? If it's useful I can make PR for this feature

**Comment by colega** [comment]
Looks like you're looking for the [`Usage`](https://github.com/kelseyhightower/envconfig/blob/master/usage.go#L113) function: it [can render](https://github.com/kelseyhightower/envconfig/blob/master/usage_test.go#L120-L129) a [plain list](https://github.com/kelseyhightower/envconfig/blob/master/testdata/custom.txt) with a custom format, or even [richer formats](https://github.com/kelseyhightower/envconfig/blob/master/testdata/default_table.txt)

**Comment by MistaTwista** [comment]
This is exactly what I need. I missed it somehow, sorry :(
