### ISSUE TITLE
Set `split_words` as a global option

### ISSUE THREAD

**Issue by abeMedia** [kelseyhightower/envconfig#190]
Right now I'm having to add the `split_words` tag to almost every single field in the struct. It would be great if this could be set as a global option.

**Comment by stigok** [comment]
This would be breaking so many builds. Already closed here #122

**Comment by abeMedia** [comment]
I never suggested setting it as default but having a global option

**Comment by stigok** [comment]
> I never suggested setting it as default but having a global option

You are right, I'm sorry. I jumped to conclusions after misinterpreting the title.

**Comment by abeMedia** [comment]
Good point... The title is a bit misleading!

**Comment by brianmaissy** [comment]
Did this ever make it in? Looks like the linked PR was into master of the fork, not the upstream?

**Comment by abemedia** [comment]
The last release was 2019 so I think it's safe to say you'll need to fork it if you want the feature.
