### ISSUE TITLE
Possibility to set slice values through environment variables.

### ISSUE THREAD

**Issue by m4ng0squ4sh** [kelseyhightower/envconfig#20]
It would be great to set slice values of default types through environment variables.

A possible syntax for slices could be:
`STRING_SLICE="item1, item2, item3, item4"`
or
`STRING_SLICE="'item1', 'item2', 'item3', 'item4'"`

**Comment by lex-r** [comment]
+1

**Comment by kelseyhightower** [comment]
This should now be working on master.
