### ISSUE TITLE
Getting some strange behaviour when setting both envconfig: and default: tag on a single field

### ISSUE THREAD

**Issue by robvdl** [kelseyhightower/envconfig#26]
I want to use both the tags envconfig:"multi_word_var" and default:"value" together on a struct field but it doesn't seem to work and I am getting some strange behaviour when I combine these.  The behaviour even changes when you change the order of them (either default: first or envconfig: first).

It is working fine when I am only using one of these tags on a field, but it seems to not work properly when I put both tags on a field.

I was expecting it would try to use the environment variable first (as defined by the envconfig: tag) and if that didn't exist, use the default value defined by the default: tag.  This is not the behaviour I am getting however.

It is looking like you can't use these tags together.on a single field.

**Comment by dimfeld** [comment]
This works fine for me. Since you say the order matters, maybe you are specifying the tags incorrectly and the Go parser is only picking up the first one? How did you write it out?

**Comment by robvdl** [comment]
I see, sorry about this, closing the issue then.
