### ISSUE TITLE
Primary goals for next release

### ISSUE THREAD

**Issue by teepark** [kelseyhightower/envconfig#40]
I've been thinking about what to try and get into the next release, and thought I'd put it here for comment.

What I'm largely focused on is getting to rough parity with stdlib examples of the "use reflect to deserialize into `interface{}`" -- thinking mainly about `encoding/json` and `database/sql`.

### Nested struct support
This will be especially useful for eliminating boilerplate when configuring option or client structs for libraries. I'd like to get this in soon.

### Pointer field support
Particularly for nested structs above (fields of pointer-to-struct are so common), but in the general case if we support decoding into a `type` then it should be pretty straightforward to decode into a `*type`. In our case it's not as simple as it should be, there's a little refactoring necessary.

json and sql both do this, and it can be useful for differentiating the zero value of a type from "wasn't set at all" (in which case it remains `nil`).

Anything else I'm missing?

**Comment by davidkbainbridge** [comment]
Given any thought to adding a "help" or "usage" capability to this tool. For example does `./myapp -h` now need to display the environment variables the caller is able to set?

**Comment by teepark** [comment]
@davidkbainbridge I think you're totally on to something!

I don't know that there's precedent for triggering a usage message via a config variable, but it would be extremely useful (I've been wanting it myself for a while) to have a way to extract the list of supported environment variables from a config struct.

What do you think about something like a `func(interface{}) map[string]string` that takes a struct you might pass to `Process()` and returns the environment variable names mapped to their types? Could be useful for integrating into a flags-driven help/usage message?

**Comment by davidkbainbridge** [comment]
Presumably we can get the names and the types already from the struct that is passed to envconfig, so wouldn't all that is needed is really the description string (short / long). This could be added as an additional tag to the struct, although that might get a bit messy:

```
type Spec struct {
        Name string `default:foobar desc:"the name to use when publishing messages"
}
```

it might be nice to support a longer description as well, but then tags get really messy.

**Comment by teepark** [comment]
I agree about the messiness of adding descriptions to the tags. I don't know that going all the way to producing a usage string is in scope, since using `flag` for that is so idiomatic, and we really don't need to be in competition.

On a tangent though, this conversation does make me want a `flagconfig` package exposing a similar `Process()` function that populates a struct, looking at the field types and creating appropriate flags for them.

**Comment by davidkbainbridge** [comment]
I think it is an interesting tension between "flags" and "envconfig". As a "12 factor app" are you meant to support both? of do you only support environment based config, with which most people are not familiar. If both, then you really want to drive both from a "single source" so as to not duplicate work.

**Comment by teepark** [comment]
I recently read this [here](https://peter.bourgon.org/go-best-practices-2016/#configuration):

> 12-factor apps encourage you to use environment vars for configuration, and I think that’s fine, provided each var is also defined as a flag. Explicitness is important: changing the runtime behavior of an application should happen in ways that are discoverable and documented.

I wish @peterbourgon gave a justification for why you should support flag-based overrides (I don't see the connection with explicitness), but his is generally a voice I trust. And that's a pattern I see a lot: an option is supported both in env var and flag form with the flag taking precedence. I suspect it's about user convenience (env vars for production use under a supervisor, but still be friendly for foreground terminal use). I'm pretty sure 12 factor isn't recommending it though.

Supporting both via `envconfig` and a hypothetical `flagconfig` would be amazing if you could drive both off of the same struct (instance even), handling the priority by just running `flagconfig` second.

**Comment by peterbourgon** [comment]
Flags are important because it's important to be able to discover the configuration surface area of a binary at rest. They're documentation.

**Comment by teepark** [comment]
So `flags` mainly for the usage message, not even hardly for the flags. Seems like we could totally meet that requirement if we could get good usage messages from `envconfig`.

**Comment by davidkbainbridge** [comment]
So a couple of thoughts while walking the dog. I like the idea of using tags on the struct for the description as this is also where defaults, etc can be defined. Providing "meta" data in another structure means keeping bits of code in sync, which is always a source of errors.

Tags on the structure to describe the usage can be messy as it leads to a long tag string. But, alternatively the tag on the structure could reference to a key in a localization file. This way, if there is a localization file the struct tag can be short (less messy), but if you want to do it all in line and deal with the messy that works too. (acknowledge that a separate localization file really gets us back to the sync issue, but it does allow usage descriptions in alternate languages)

As for flags, it seems perfectly reasonable to use the flags package in addition to the envconfig package and if you want -h to show envconfig usage then capture the `-h` flag and call a envconfig method to display usage and exit. If support for a `-h` wants to be added to envconfig so you don't also have to import `flags` for such a small task, then that can be done as well.

**Comment by davidkbainbridge** [comment]
So the following is what i have, being driven off struct tags. Not sure I love the format, but ...
```
USAGE: cord-maas-automation

  This application is configured via the environment. The following environment
  variables can used specified:

  MAAS_AUTOMATION_API_KEY
    [description] API key used when connecting to MAAS
    [type]        string
    [default]
  MAAS_AUTOMATION_MAAS_URL
    [description] URL on which to connect to MAAS
    [type]        string
    [default]     http://localhost/MAAS
  MAAS_AUTOMATION_API_VERSION
    [description] MAAS API version to utilized, current 1.0 only
    [type]        string
    [default]     1.0
  MAAS_AUTOMATION_QUERY_PERIOD
    [description] How long to wait between queries to MAAS
    [type]        string
    [default]     15s
  MAAS_AUTOMATION_PREVIEW
    [description] Output what actions would be taken, but don't take them
    [type]        bool
    [default]     false
  MAAS_AUTOMATION_MAPPINGS
    [description] Mapping from NIC MAC address to hostname
    [type]        string
    [default]     {}
  MAAS_AUTOMATION_ALWAYS_RENAME
    [description] Attempt to rename host at every step
    [type]        bool
    [default]     true
  MAAS_AUTOMATION_VERBOSE
    [description] Output verbose logging
    [type]        bool
    [default]     false
  MAAS_AUTOMATION_FILTER_SPEC
    [description] Filter which nodes to include or exclude
    [type]        string
    [default]
```

**Comment by teepark** [comment]
Let's promote this to it's own issue and work out the specifics there. @davidkbainbridge would you mind creating it?

**Comment by davidkbainbridge** [comment]
got it
