### ISSUE TITLE
CamelCase -> Underscores

### ISSUE THREAD

**Issue by karlkfi** [kelseyhightower/envconfig#60]
Would be pretty useful to have a configuration option in `Process` that automatically inserts underscores for camel case field names, as in your `MultiWordVar ->  MYAPP_MULTI_WORD_VAR` example. Just because it's tedious to specify custom `envconfig` annotations for every field.

**Comment by relistan** [comment]
#66 Should close this when it's merged.

**Comment by karlkfi** [comment]
Yay!
