### ISSUE TITLE
Please make a new release (tag)

### ISSUE THREAD

**Issue by AlekSi** [kelseyhightower/envconfig#63]
There are [27 commits](https://github.com/kelseyhightower/envconfig/compare/1.1.0...master) since 1.1.0.
Also, may you please add tag `v1.1.0` to `1.1.0`? Right now you have `v1.0.0` and `1.1.0`, styles are different.

**Comment by teepark** [comment]
- [x] v1.1.0 tag
- [ ] next release

https://github.com/kelseyhightower/envconfig/pull/62 with `Usage()` and `UsageF()` is a pretty big deal, how about I cut a release when that gets merged?

<sub>pls remind me again if I forget.</sub>

**Comment by teepark** [comment]
#62 has been stalled long enough, so I just cut tag v1.2.0

**Comment by AlekSi** [comment]
@teepark May you also make a [release](https://github.com/kelseyhightower/envconfig/releases)?
