### ISSUE TITLE
Question regarding naming of Specification struct

### ISSUE THREAD

**Issue by itsjamie** [kelseyhightower/envconfig#68]
Just curious where "Specification" came as a name for the example that stores configuration coming from the environment.

Thanks!

**Comment by teepark** [comment]
Good question -- that example predates my contributing, but I kind of read it like this:

The type definition for the pointer you pass to `Process` acts as a specification for the environment variables your program accepts (to understand the environment variable interface of a program you'd look at that struct). For what I assume is the same reason, the argument in the definition of `Process` is named `"spec"`.

**Comment by itsjamie** [comment]
Thanks for the explanation @teepark.
