### ISSUE TITLE
Map Support

### ISSUE THREAD

**Issue by robertmeta** [kelseyhightower/envconfig#70]
I was curious if a patch to add map support would be accepted, I found MendelGusmao's work on this (https://github.com/MendelGusmao/envconfig) is very dated by seems like it could be a reasonable approach.

**Comment by teepark** [comment]
Great idea @robertmeta!

Forgive me but I took a stab at it myself: #73. I'll leave that PR up for at least few days for feedback -- I'd appreciate your thoughts!
