### ISSUE TITLE
Empty string for required fields

### ISSUE THREAD

**Issue by yanpozka** [kelseyhightower/envconfig#71]
So far if we export an environment variable with an empty value the **required** tag will not complaint.
For example in this sceneario, _Process()_ method will not return an error.
Is this an expected behavior ?

```bash
export MYAPP_USER=
export MYAPP_USERS=""
```

```go
type Specification struct {
    User    string
    Users   []string
}
```

**Comment by teepark** [comment]
Yes, this is intentional. The empty string is still a value, and `required` only asserts that the variable exists. See #29.

Want to make this more clear in the README? I'd happily merge a PR for that.
