### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by qrpike** [kelseyhightower/envconfig#72]
I'm guessing this is due to me using the latest "Release" which glide uses by default, could you please publish a new release with the `split_words` enabled?

Thanks,

**Comment by teepark** [comment]
Hi @qrpike!
Yes absolutely, I'll set up a new release.

In the meantime, you can edit `glide.yaml` in your project to point at the current master revision to get unblocked:
```yaml
- package: github.com/kelseyhightower/envconfig
  version: 4069f29f08928c54bcb1fdf632b31b1bb54b4fdb
```
I'll also let you know here when that release is done so you can switch it back to semver.

**Comment by teepark** [comment]
@qrpike -- I just pushed up a `v1.3.0` tag, so you should be able to get the latest via semver now!

**Comment by qrpike** [comment]
@teepark Thanks!
