### ISSUE TITLE
[Feature Request] Self-Documenting?

### ISSUE THREAD

**Issue by b3ntly** [kelseyhightower/envconfig#93]
Could this be made self-documenting similar to spf13/cobra? What would be the best way to implement this? 

I personally like markdown tables for repositories of applications intended to be run through docker. Is this out of scope for the package?

**Comment by teepark** [comment]
What do you mean by self-documenting? Sorry, I'm not familiar with spf13/cobra.

We do have the [`Usage/Usaget/Usagef`](https://godoc.org/github.com/kelseyhightower/envconfig#Usage) family of functions for dumping out info about the supported environment variables. Does that qualify?

**Comment by b3ntly** [comment]
Usage was what I was looking for! My goal is to generate an output similar to the one shown [here](https://github.com/b3ntly/twelvefactor_databases). I should be able to generate the markdown somewhere in my CI/CD pipeline with help from Usagef(), I should've checked the GoDoc first, thanks.

**Comment by owulveryck** [comment]
For the record, here is an example (I use it on a personal project):

```go
import (
	"bytes"
	"io"
	"text/tabwriter"

	"github.com/kelseyhightower/envconfig"
)

const (
	mdFormat = `| KEY	| TYPE	| DEFAULT	| REQUIRED	| DESCRIPTION	|
| 	| 	| 	| 	| 	|
{{range .}}| {{ usage_key . }}	| {{usage_type .}}	| {{usage_default .}}	| {{usage_required .}}	| {{usage_description .}}	|
{{end}}`
)

func Usage(prefix string, spec interface{}, output io.Writer) {
	var b bytes.Buffer
	tabs := tabwriter.NewWriter(&b, 1, 0, 4, ' ', 0)
	envconfig.Usagef(prefix, spec, tabs, mdFormat)
	tabs.Flush()
	// replace the second line's spaces by dash
	bytes := b.Bytes()
	lines := 0
	for i, b := range bytes {
		if b == '\n' {
			lines++
		}
		if lines == 1 && b == ' ' {
			bytes[i] = '-'
		}
	}
	io.Copy(output, &b)
}
```
